libpwquality: fix Nothing RPROVIDES 'lib32-python3-libpwquality'
While multilib enabled, if other recipe RDEPENDS python3-libpwquality,
it failed with:
...
ERROR: Nothing RPROVIDES 'lib32-python3-libpwquality'
...

Do not use python3-${PN} could fix the issue.

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
(cherry picked from commit 3c73befc036fed4506c9bb8adc6c615dd2d2999c)
Signed-off-by: Armin Kuster <akuster808@gmail.com>