libreport: fix Nothing RPROVIDES 'lib32-python3-libreport'
While multilib enabled, if other recipe RDEPENDS python3-libreport,
it failed with:
...
ERROR: Nothing RPROVIDES 'lib32-python3-libreport'
...

Do not use python3-${PN} could fix the issue.

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
(cherry picked from commit 5d6d21e98ed594809169d2b2f6964e90a3369a96)
Signed-off-by: Armin Kuster <akuster808@gmail.com>